document.writeln("<footer>");
document.writeln("	<div class=\"foot_top clearfix\">");
document.writeln("		<a href=\"#\">登录</a>");
document.writeln("		<a href=\"#\">注册</a>");
document.writeln("		<a href=\"#\">");
document.writeln("			<img src=\"images/top.jpg\">");
document.writeln("		返回顶部</a>");
document.writeln("	</div>");
document.writeln("	<div class=\"foot_info\">");
document.writeln("		<p>");
document.writeln("			<a href=\"http://m.manmanbuy.com/?o=download\" style=\"color: Red;\">手机APP下载</a>");
document.writeln("			<a href=\"http://m.manmanbuy.com\" style=\"color: #5a5a5a\">");
document.writeln("                    慢慢买手机版</a>");
document.writeln("            -- 掌上比价平台");
document.writeln("		</p>");
document.writeln("		<p>");
document.writeln("            m.manmanbuy.com  ");
document.writeln("		</p>");
document.writeln("	</div>");
document.writeln("</footer>");