document.writeln("<!-- S=头部 -->");
document.writeln("");
document.writeln("	<header class=\"mainColor clearfix\">");
document.writeln("		<div class=\"fl logo\">");
document.writeln("			<a href=\"http://m.manmanbuy.com/\">");
document.writeln("				<img src=\"images/header_logo.png\">");
document.writeln("			</a>");
document.writeln("		</div>");
document.writeln("		<div class=\"fr appdown\">");
document.writeln("			<a href=\"http://m.manmanbuy.com/?o=download\">");
document.writeln("				<img src=\"images/header_app.png\">");
document.writeln("			</a>");
document.writeln("		</div>");
document.writeln("	</header>");
document.writeln("");
document.writeln("<!-- E=头部 -->");
document.writeln("");
document.writeln("<!-- S=搜索 -->");
document.writeln("	<form class=\"search\">");
document.writeln("		<input class=\"search_box\" type=\"search\" placeholder=\"请输入你想比价的商品\">");
document.writeln("		<input class=\"search_btn mainColor\" type=\"submit\" value=\"搜索\">");
document.writeln("	</form>");
document.writeln("");
document.writeln("<!-- E=搜索 -->");